URL = "192.168.50.4"
# export DOCKER_HOST="192.168.50.4:5422"

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :private_network, ip: URL
  config.vm.provision :docker do |d|
    d.pull_images "ubuntu"
  end
end
